services:
  api:
    build: ./backend
    container_name: student-api
    ports:
      - "3000:3000"
    environment:
      PORT: 3000
      MONGO_URI: mongodb://mongodb:27017/campusconnect
      CORS_ORIGIN: http://localhost:5173
    depends_on:
      - mongodb
    networks:
      - student-network
  mongodb:
    image: mongo:7
    container_name: mongodb
    volumes:
      - student-mongo-data:/data/db
    networks:
      - student-network
volumes:
  student-mongo-data:
networks:
  student-network:
