services:
  - type: web
    name: campusconnect-api-gateway
    runtime: docker
    plan: free
    region: singapore
    dockerfilePath: microservices/api-gateway/Dockerfile
    dockerContext: microservices/api-gateway
    healthCheckPath: /health

  - type: web
    name: campusconnect-user-service
    runtime: docker
    plan: free
    region: singapore
    dockerfilePath: microservices/user-service/Dockerfile
    dockerContext: microservices/user-service

  - type: web
    name: campusconnect-product-service
    runtime: docker
    plan: free
    region: singapore
    dockerfilePath: microservices/product-service/Dockerfile
    dockerContext: microservices/product-service

  - type: web
    name: campusconnect-order-service
    runtime: docker
    plan: free
    region: singapore
    dockerfilePath: microservices/order-service/Dockerfile
    dockerContext: microservices/order-service
