apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: campusconnect-services
  namespace: lab8
  labels:
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      monitoring: prometheus
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
