apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  labels:
    app: api-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
        - name: api-gateway
          image: campusconnect-api-gateway:lab8
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: GATEWAY_PORT
              valueFrom:
                configMapKeyRef: { name: campusconnect-config, key: GATEWAY_PORT }
            - name: USER_SERVICE_URL
              valueFrom:
                configMapKeyRef: { name: campusconnect-config, key: USER_SERVICE_URL }
            - name: PRODUCT_SERVICE_URL
              valueFrom:
                configMapKeyRef: { name: campusconnect-config, key: PRODUCT_SERVICE_URL }
            - name: ORDER_SERVICE_URL
              valueFrom:
                configMapKeyRef: { name: campusconnect-config, key: ORDER_SERVICE_URL }
