apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
  labels:
    app: order-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
        - name: order-service
          image: campusconnect-order-service:lab8
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3003
          env:
            - name: ORDER_SERVICE_PORT
              valueFrom:
                configMapKeyRef: { name: campusconnect-config, key: ORDER_SERVICE_PORT }
            - name: USER_SERVICE_URL
              valueFrom:
                configMapKeyRef: { name: campusconnect-config, key: USER_SERVICE_URL }
            - name: PRODUCT_SERVICE_URL
              valueFrom:
                configMapKeyRef: { name: campusconnect-config, key: PRODUCT_SERVICE_URL }
