apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service
  labels:
    app: product-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product-service
  template:
    metadata:
      labels:
        app: product-service
    spec:
      containers:
        - name: product-service
          image: campusconnect-product-service:lab8
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3002
          env:
            - name: PRODUCT_SERVICE_PORT
              valueFrom:
                configMapKeyRef: { name: campusconnect-config, key: PRODUCT_SERVICE_PORT }
